'use client';

import { useState, useEffect } from 'react';
import { useSearchParams, useRouter } from 'next/navigation';
import { BlurFade } from '../ui/blur-fade';
import { BorderBeam } from '../ui/border-beam';
import { ShimmerButton } from '../ui/shimmer-button';
import {
  Wand2,
  Layout,
  Tv,
  Image as ImageIcon,
  Zap,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  Sparkles,
  Loader2,
  Download
} from 'lucide-react';
import { generateProfessionalFilename, downloadRemoteImage } from '@/lib/download-utils';
import Input from '../shared/Input';
import Button from '../shared/Button';
import ErrorMessage from '../shared/ErrorMessage';
import useChannels from '../../hooks/useChannels';
import useArchetypes from '../../hooks/useArchetypes';
import useGenerate from '../../hooks/useGenerate';

interface GenerateFormProps {
  initialData?: any;
}

export default function GenerateForm({ initialData }: GenerateFormProps) {
  const router = useRouter();
  const { channels } = useChannels();
  const [selectedChannelId, setSelectedChannelId] = useState(initialData?.channelId || '');
  const { archetypes } = useArchetypes(selectedChannelId);
  const { loading, error, success, result, generateThumbnail, reset } = useGenerate();

  const searchParams = useSearchParams();
  const redoJobId = searchParams.get('jobId');

  const selectedArchetype = archetypes.find((a: any) => a.id === archetypeId);
  const [archetypeId, setArchetypeId] = useState(initialData?.archetypeId || '');
  const [videoTopic, setVideoTopic] = useState(initialData?.videoTopic || initialData?.videoTitle || ''); // Handle both
  const [thumbnailText, setThumbnailText] = useState(initialData?.thumbnailText || '');
  const [softwareSubject, setSoftwareSubject] = useState(initialData?.softwareSubject || '');
  const [draftPrompt, setDraftPrompt] = useState(initialData?.promptUsed || '');
  const [autoGeneratedPrompt, setAutoGeneratedPrompt] = useState(''); // Track auto-generated prompt
  const [showDraftPrompt, setShowDraftPrompt] = useState(!!initialData?.promptUsed);
  const [archetypeSearch, setArchetypeSearch] = useState('');
  const [versionCount, setVersionCount] = useState(1);
  const [includeBrandColors, setIncludeBrandColors] = useState(false);
  const [includePersona, setIncludePersona] = useState(true);
  const [validationErrors, setValidationErrors] = useState<{
    channelId?: string;
    archetypeId?: string;
    videoTopic?: string;
    thumbnailText?: string;
  }>({});

  // Handle external population (Redo functionality) when already mounted
  useEffect(() => {
    if (initialData) {
      setSelectedChannelId(initialData.channelId || '');
      setArchetypeId(initialData.archetypeId || '');
      setVideoTopic(initialData.videoTopic || initialData.videoTitle || '');
      setThumbnailText(initialData.thumbnailText || '');
      setSoftwareSubject(initialData.softwareSubject || '');
      setDraftPrompt(initialData.promptUsed || '');
      setShowDraftPrompt(!!initialData.promptUsed);
    }
  }, [initialData]);

  // Load job for Redo if jobId exists
  useEffect(() => {
    if (redoJobId && channels.length > 0) {
      const loadJobForRedo = async () => {
        try {
          const response = await fetch(`/api/jobs/${redoJobId}`);
          if (!response.ok) return;
          const jobData = await response.json();

          setSelectedChannelId(jobData.channelId || '');
          setArchetypeId(jobData.archetypeId || '');
          setVideoTopic(jobData.videoTopic || '');
          setThumbnailText(jobData.thumbnailText || '');
          setSoftwareSubject(jobData.softwareSubject || '');
          setDraftPrompt(jobData.customPrompt || '');
          if (jobData.customPrompt) setShowDraftPrompt(true);
        } catch (err) {
          console.error('[REDO] Load error:', err);
        }
      };
      loadJobForRedo();
    }
  }, [redoJobId, channels.length]);

  // Auto-populate exact prompt via API when selections change
  useEffect(() => {
    if (!selectedChannelId || !archetypeId || !videoTopic) return;
    
    const fetchPreview = async () => {
      try {
        const response = await fetch('/api/preview-prompt', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            channelId: selectedChannelId,
            archetypeId,
            videoTopic,
            thumbnailText,
            softwareSubject: softwareSubject.trim(),
            includeBrandColors,
            includePersona
          })
        });

        if (response.ok) {
          const data = await response.json();
          if (data.prompt) {
            setDraftPrompt(data.prompt);
            setAutoGeneratedPrompt(data.prompt); // Store auto-generated version
          }
        } else {
          const errorData = await response.json();
          console.error('Preview prompt API error:', errorData.error || response.statusText);
          // Optionally clear draft prompt on error
          setDraftPrompt('');
          setAutoGeneratedPrompt('');
        }
      } catch (err) {
        console.error('Failed to preview prompt:', err);
        // Clear draft prompt on network error
        setDraftPrompt('');
      }
    };
    
    // Debounce to prevent spamming the fast API
    const timer = setTimeout(() => fetchPreview(), 500);
    return () => clearTimeout(timer);
  }, [selectedChannelId, archetypeId, videoTopic, thumbnailText, includeBrandColors, includePersona]);

  // Reset form fields when channel changes (prevent state bleeding across channels)
  useEffect(() => {
    setArchetypeId('');
    setVideoTopic('');
    setThumbnailText('');
    setDraftPrompt('');
  }, [selectedChannelId]);

  // V32: Implement State Persistence via sessionStorage
  useEffect(() => {
    const savedState = sessionStorage.getItem('generate_form_state');
    if (savedState) {
      try {
        const state = JSON.parse(savedState);
        if (state.selectedChannelId) setSelectedChannelId(state.selectedChannelId);
        if (state.archetypeId) setArchetypeId(state.archetypeId);
        if (state.videoTopic) setVideoTopic(state.videoTopic);
        if (state.thumbnailText) setThumbnailText(state.thumbnailText);
        if (state.softwareSubject) setSoftwareSubject(state.softwareSubject);
        if (state.draftPrompt) setDraftPrompt(state.draftPrompt);
        if (state.versionCount) setVersionCount(state.versionCount);
        if (state.showDraftPrompt) setShowDraftPrompt(state.showDraftPrompt);
        if (state.includeBrandColors !== undefined) setIncludeBrandColors(state.includeBrandColors);
        if (state.includePersona !== undefined) setIncludePersona(state.includePersona);
      } catch (e) {
        console.error('Failed to load form state', e);
      }
    }
  }, []);

  useEffect(() => {
    const state = {
      selectedChannelId,
      archetypeId,
      videoTopic,
      thumbnailText,
      softwareSubject,
      draftPrompt,
      versionCount,
      showDraftPrompt,
      includeBrandColors,
      includePersona
    };
    sessionStorage.setItem('generate_form_state', JSON.stringify(state));
  }, [selectedChannelId, archetypeId, videoTopic, thumbnailText, softwareSubject, draftPrompt, versionCount, showDraftPrompt, includeBrandColors, includePersona]);

  const validate = (): boolean => {
    const errors: any = {};

    if (!selectedChannelId) {
      errors.channelId = 'Please select a channel';
    }

    if (!archetypeId) {
      errors.archetypeId = 'Please select an archetype';
    }

    if (!videoTopic.trim()) {
      errors.videoTopic = 'Video topic is required';
    }

    if (!thumbnailText.trim()) {
      errors.thumbnailText = 'Thumbnail text is required';
    }

    setValidationErrors(errors);
    return Object.keys(errors).length === 0;
  };

  const handleDownload = async (url: string, index: number) => {
    try {
      const channel = channels.find((c: any) => c.id === selectedChannelId);
      const archetype = archetypes.find((a: any) => a.id === archetypeId);

      const filename = generateProfessionalFilename(
        channel?.name || 'Channel',
        archetype?.category || 'General',
        videoTopic || 'Thumbnail',
        index + 1
      );

      await downloadRemoteImage(url, filename);
    } catch (error) {
      console.error('Download failed:', error);
      alert('Failed to download image. Please try again or right-click to save manually.');
    }
  };

  const handleSubmit = async (e?: React.FormEvent) => {
    e?.preventDefault();

    if (!validate()) return;

    try {
      // Only send customPrompt if user actually modified it from auto-generated version
      const userModifiedPrompt = draftPrompt.trim() !== autoGeneratedPrompt.trim() && draftPrompt.trim();

      await generateThumbnail({
        channelId: selectedChannelId,
        archetypeId,
        videoTopic: videoTopic.trim(),
        thumbnailText: thumbnailText.trim(),
        softwareSubject: softwareSubject.trim(),
        customPrompt: userModifiedPrompt || undefined,
        versionCount,
        includeBrandColors,
        includePersona,
      });

      // Redirect to history page after successfully queueing jobs
      router.push('/dashboard?tab=history');
    } catch (err) {
      // Error is handled by useGenerate hook
    }
  };

  const handleReset = () => {
    reset();
    setSelectedChannelId('');
    setArchetypeId('');
    setVideoTopic('');
    setThumbnailText('');
    setDraftPrompt('');
    setVersionCount(1);
    setShowDraftPrompt(false);
    setValidationErrors({});
  };

  const handleRedo = () => {
    handleSubmit();
  };

  return (
    <div className="generate-container">
      <BlurFade delay={0.1}>
        <div className="view-header">
          <h2 className="view-title">Generate Thumbnail</h2>
          <p className="view-subtitle">Transform your video ideas into high-converting visual assets</p>
        </div>
      </BlurFade>

      <form onSubmit={handleSubmit} className="form-wrapper">
          {error && <ErrorMessage message={error} onDismiss={() => reset()} />}

          <div className="form-grid">
            <BlurFade delay={0.2} direction="right">
              <div className="form-column glass">
                <div className="column-content">
                  <div className="column-header">
                    <Tv size={18} className="text-muted-foreground" />
                    <h3 className="column-title">Source Details</h3>
                  </div>
                  <div className="field-group">
                    <label className="field-label">
                      Channel <span className="required">*</span>
                    </label>
                    <select
                      value={selectedChannelId}
                      onChange={(e) => setSelectedChannelId(e.target.value)}
                      disabled={loading}
                      className={`form-select ${validationErrors.channelId ? 'has-error' : ''}`}
                      title="Select Channel"
                    >
                      <option value="">Select a channel</option>
                      {channels.map((channel: any) => (
                        <option key={channel.id} value={channel.id}>
                          {channel.name}
                        </option>
                      ))}
                    </select>
                    {validationErrors.channelId && (
                      <div className="error-text">{validationErrors.channelId}</div>
                    )}
                  </div>

                  <div className="field-group">
                    <label className="field-label">
                      Archetype <span className="required">*</span>
                    </label>
                    <div className="search-box">
                      <Input
                        placeholder="Search archetypes..."
                        value={archetypeSearch}
                        onChange={setArchetypeSearch}
                        className="search-input"
                      />
                    </div>
                    <div className={`archetype-list-container ${!selectedChannelId || loading ? 'disabled' : ''} ${validationErrors.archetypeId ? 'has-error' : ''}`}>
                      {!selectedChannelId ? (
                        <div className="archetype-placeholder">Select a channel first</div>
                      ) : archetypes.length === 0 ? (
                        <div className="archetype-placeholder">No archetypes for this channel</div>
                      ) : (
                        <div className="archetype-list">
                          {archetypes
                            .filter((a: any) => a.name.toLowerCase().includes(archetypeSearch.toLowerCase()) || a.category?.toLowerCase().includes(archetypeSearch.toLowerCase()))
                            .map((archetype: any) => (
                              <div
                                key={archetype.id}
                                className={`archetype-list-item ${archetypeId === archetype.id ? 'selected' : ''}`}
                                onClick={() => !loading && setArchetypeId(archetype.id)}
                                title={archetype.layoutInstructions}
                              >
                                <div className="archetype-list-thumbnail">
                                  <img src={archetype.imageUrl} alt={archetype.name} />
                                </div>
                                <div className="archetype-list-content">
                                  <div className="archetype-list-name">{archetype.name}</div>
                                  <div className="archetype-list-category">{archetype.category || 'General'}</div>
                                </div>
                                {archetypeId === archetype.id && (
                                  <div className="archetype-list-check">✓</div>
                                )}
                              </div>
                            ))
                          }
                        </div>
                      )}
                    </div>
                    {archetypeId && (
                      <div className="archetype-preview-card glass-dark">
                        <img
                          src={archetypes.find((a: any) => a.id === archetypeId)?.imageUrl}
                          alt="Archetype reference"
                          className="archetype-preview-img"
                        />
                        <div className="archetype-preview-info">
                          <span className="archetype-preview-tag">{archetypes.find((a: any) => a.id === archetypeId)?.category || 'General'}</span>
                          <p className="archetype-preview-instructions">{archetypes.find((a: any) => a.id === archetypeId)?.layoutInstructions}</p>
                        </div>
                      </div>
                    )}
                    {validationErrors.archetypeId && (
                      <div className="error-text">{validationErrors.archetypeId}</div>
                    )}
                  </div>

                  <div className="advanced-toggle">
                    <button
                      type="button"
                      className={`toggle-btn ${showDraftPrompt ? 'active' : ''}`}
                      onClick={() => setShowDraftPrompt(!showDraftPrompt)}
                      disabled={loading}
                    >
                      <span className="icon">{showDraftPrompt ? <ChevronDown size={14} /> : <ChevronRight size={14} />}</span>
                      Editable Generation Prompt
                    </button>
                  </div>

                  {showDraftPrompt && (
                    <BlurFade delay={0.1}>
                      <div className="advanced-content">
                        <Input
                          label="Prompt Draft"
                          value={draftPrompt}
                          onChange={setDraftPrompt}
                          placeholder="This prompt will be sent to the AI..."
                          multiline
                          rows={6}
                          disabled={loading}
                        />
                        <p className="field-hint">
                          You can manually tweak the AI's instructions here before generating.
                          <span style={{ marginLeft: '8px', color: draftPrompt.length > 5000 ? '#ef4444' : '#71717a' }}>
                            Character count: {draftPrompt.length} / 5000
                          </span>
                        </p>

                        <div className="advanced-toggles-grid">
                          <label className="checkbox-label">
                            <input
                              type="checkbox"
                              checked={includeBrandColors}
                              onChange={(e) => setIncludeBrandColors(e.target.checked)}
                              disabled={loading}
                              className="custom-checkbox"
                            />
                            <span className="checkbox-text">Include Brand Colors</span>
                          </label>
                          <label className="checkbox-label">
                            <input
                              type="checkbox"
                              checked={includePersona}
                              onChange={(e) => setIncludePersona(e.target.checked)}
                              disabled={loading}
                              className="custom-checkbox"
                            />
                            <span className="checkbox-text">Include Persona (if available)</span>
                          </label>
                        </div>
                      </div>
                    </BlurFade>
                  )}
                </div>
              </div>
            </BlurFade>

            <BlurFade delay={0.3} direction="left">
              <div className="form-column glass">
                <div className="column-content">
                  <div className="column-header">
                    <Sparkles size={18} className="text-muted-foreground" />
                    <h3 className="column-title">Content Generation</h3>
                  </div>
                  <Input
                    label="Video Topic"
                    value={videoTopic}
                    onChange={setVideoTopic}
                    placeholder="e.g., How to build a high-IQ Vibe Coder app"
                    required
                    error={validationErrors.videoTopic}
                    disabled={loading}
                  />

                  <Input
                    label="Thumbnail Text"
                    value={thumbnailText}
                    onChange={setThumbnailText}
                    placeholder="e.g., VIBE CODER"
                    required
                    error={validationErrors.thumbnailText}
                    disabled={loading}
                    maxLength={50}
                  />

                  <Input
                    label="Software/Subject (Optional)"
                    value={softwareSubject}
                    onChange={setSoftwareSubject}
                    placeholder="e.g., WhatsApp, Notion, PowerPoint"
                    disabled={loading}
                    maxLength={50}
                    description={
                      selectedArchetype?.featuresLogo
                        ? "This archetype supports logo replacement"
                        : "Only used if archetype features a replaceable logo"
                    }
                  />

                  <div className="generation-status">
                    {loading ? (
                      <div className="loading-state-premium glass-dark relative overflow-hidden">
                        <BorderBeam size={200} duration={4} colorFrom="#ffffff" colorTo="#333333" />
                        <div className="loading-content">
                          <div className="animation-container">
                            <div className="sparkle-orbit">
                              <Sparkles className="premium-sparkle-main" size={48} />
                            </div>
                            <div className="scan-line" />
                          </div>
                          <div className="status-text-premium">
                            <h4 className="animate-pulse">Titan AI is Crafting...</h4>
                            <p>Synthesizing {versionCount} High-IQ Version{versionCount > 1 ? 's' : ''}</p>
                            <div className="progress-bar-container">
                              <div className="progress-bar-fill animate-shimmer" />
                            </div>
                          </div>
                        </div>
                      </div>
                    ) : (
                      <div className="info-card glass">
                        <div className="info-icon"><Zap size={18} /></div>
                        <p>AI will analyze your selected archetype and video topic to create a high-converting thumbnail.</p>
                      </div>
                    )}
                  </div>

                  <div className="field-group version-selector">
                    <label className="field-label">Versions to Generate</label>
                    <div className="version-controls">
                      {[1, 2, 3, 4].map((v) => (
                        <button
                          key={v}
                          type="button"
                          className={`version-btn ${versionCount === v ? 'active' : ''}`}
                          onClick={() => setVersionCount(v)}
                          disabled={loading}
                        >
                          {v}
                        </button>
                      ))}
                    </div>
                  </div>

                  <div className="form-actions">
                    <ShimmerButton
                      type="submit"
                      disabled={loading}
                      className="submit-btn"
                      background="linear-gradient(135deg, #667eea 0%, #764ba2 100%)"
                    >
                      <Sparkles size={18} style={{ marginRight: '0.6rem' }} />
                      {loading ? 'Creating Batch...' : `Generate ${versionCount} Version${versionCount > 1 ? 's' : ''}`}
                    </ShimmerButton>
                  </div>
                </div>
              </div>
            </BlurFade>
          </div>
        </form>

      <style jsx>{`
        .generate-container {
          max-width: 1000px;
          margin: 0 auto;
          animation: fade-in 0.6s cubic-bezier(0.16, 1, 0.3, 1);
        }

        .view-header {
          margin-bottom: 2.5rem;
        }

        .view-title {
          font-size: 2.25rem;
          font-weight: 800;
          margin: 0;
          color: #ffffff;
          letter-spacing: -0.02em;
        }

        .view-subtitle {
          color: var(--muted-foreground);
          margin-top: 0.5rem;
          font-size: 1rem;
        }

        .form-wrapper {
          display: flex;
          flex-direction: column;
          gap: 2rem;
        }

        .form-grid {
          display: grid;
          grid-template-columns: 1fr 1fr;
          gap: 3rem;
        }

        @media (max-width: 850px) {
          .form-grid {
            grid-template-columns: 1fr;
            gap: 2rem;
          }
        }

        .form-column {
          display: flex;
          flex-direction: column;
          gap: 1.5rem;
          height: 100%;
        }

        :global(.magic-wrapper) {
          height: 100%;
          display: flex;
          flex-direction: column;
        }

        .column-content {
          padding: 2rem;
          display: flex;
          flex-direction: column;
          gap: 1.5rem;
          height: 100%;
        }

        .field-group {
          display: flex;
          flex-direction: column;
          gap: 0.5rem;
        }

        .field-label {
          font-size: 0.875rem;
          font-weight: 600;
          color: var(--muted-foreground);
          letter-spacing: 0.02em;
        }

        .required {
          color: #ef4444;
        }

        .form-select {
          width: 100%;
          padding: 0.875rem 1rem;
          background: rgba(255, 255, 255, 0.03);
          border: 1px solid var(--border);
          border-radius: var(--radius);
          color: var(--foreground);
          font-family: inherit;
          font-size: 0.9375rem;
          transition: all 0.2s ease;
          outline: none;
          cursor: pointer;
          appearance: none;
          background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='none' viewBox='0 0 24 24' stroke='%2371717a' stroke-width='2'%3E%3Cpath stroke-linecap='round' stroke-linejoin='round' d='M19 9l-7 7-7-7'/%3E%3C/svg%3E");
          background-repeat: no-repeat;
          background-position: right 1rem center;
          background-size: 1rem;
        }
        
        .form-select option {
          background-color: #09090b;
          color: #fafafa;
        }

        .form-select:focus {
          border-color: #52525b;
          background-color: rgba(255, 255, 255, 0.05);
          box-shadow: 0 0 0 2px rgba(255, 255, 255, 0.05);
        }

        .form-select.has-error {
          border-color: #ef4444;
          background-color: rgba(239, 68, 68, 0.02);
        }

        .version-selector {
          margin-top: 0.5rem;
        }

        .version-controls {
          display: flex;
          gap: 0.5rem;
        }

        .version-btn {
          flex: 1;
          padding: 0.6rem;
          background: rgba(255, 255, 255, 0.03);
          border: 1px solid var(--border);
          border-radius: var(--radius);
          color: var(--muted-foreground);
          font-weight: 600;
          cursor: pointer;
          transition: all 0.2s ease;
        }

        .version-btn:hover {
          background: rgba(255, 255, 255, 0.06);
          border-color: #52525b;
        }

        .version-btn.active {
          background: #ffffff;
          color: #000000;
          border-color: #ffffff;
        }

        .error-text {
          font-size: 0.75rem;
          color: #ef4444;
          margin-top: 0.25rem;
        }

        .archetype-preview-card {
          margin-top: 1rem;
          border-radius: var(--radius);
          overflow: hidden;
          background: rgba(255, 255, 255, 0.02);
          border: 1px solid var(--border);
        }

        .archetype-preview-img {
          width: 100%;
          height: 120px;
          object-fit: cover;
          border-bottom: 1px solid var(--border);
        }

        .archetype-preview-info {
          padding: 1rem;
        }

        .archetype-preview-tag {
          font-size: 0.7rem;
          background: #ffffff;
          color: #000000;
          padding: 0.2rem 0.5rem;
          border-radius: 4px;
          font-weight: 700;
          text-transform: uppercase;
        }

        .archetype-preview-instructions {
          font-size: 0.8rem;
          color: var(--muted-foreground);
          margin-top: 0.5rem;
          line-height: 1.4;
          display: -webkit-box;
          -webkit-line-clamp: 2;
          -webkit-box-orient: vertical;
          overflow: hidden;
        }

        .advanced-toggle {
          margin-top: 0.5rem;
        }

        .toggle-btn {
          background: transparent;
          border: none;
          color: var(--muted-foreground);
          font-size: 0.875rem;
          font-weight: 500;
          cursor: pointer;
          display: flex;
          align-items: center;
          gap: 0.5rem;
          padding: 0.5rem 0;
          transition: color 0.2s ease;
        }

        .toggle-btn:hover {
          color: var(--foreground);
        }

        .toggle-btn .icon {
          font-size: 0.75rem;
          transition: transform 0.2s ease;
        }

        .toggle-btn.active .icon {
          transform: rotate(0deg);
        }

        .advanced-content {
          animation: slide-down 0.3s cubic-bezier(0.16, 1, 0.3, 1);
        }

        .advanced-toggles-grid {
          display: grid;
          grid-template-columns: 1fr 1fr;
          gap: 1rem;
          margin-top: 1rem;
        }

        .checkbox-label {
          display: flex;
          align-items: center;
          gap: 0.5rem;
          padding: 0.75rem 1rem;
          background: rgba(255, 255, 255, 0.03);
          border: 1px solid var(--border);
          border-radius: var(--radius);
          cursor: pointer;
          transition: all 0.2s ease;
        }

        .checkbox-label:hover {
          background: rgba(255, 255, 255, 0.05);
          border-color: #52525b;
        }
        
        .custom-checkbox {
          accent-color: #ffffff;
          width: 1rem;
          height: 1rem;
          cursor: pointer;
        }

        .checkbox-text {
          font-size: 0.8rem;
          color: var(--muted-foreground);
          font-weight: 500;
        }

        .generation-status {
          margin-top: auto;
        }

        .info-card {
          padding: 1.25rem;
          border-radius: var(--radius);
          display: flex;
          gap: 1rem;
          align-items: flex-start;
          font-size: 0.875rem;
          color: var(--muted-foreground);
          line-height: 1.5;
        }

        .info-icon {
          font-size: 1.25rem;
          line-height: 1;
        }

        .loading-state {
          padding: 2rem;
          border-radius: var(--radius);
          display: flex;
          flex-direction: column;
          align-items: center;
          gap: 1.5rem;
          text-align: center;
        }

        .spinner {
          width: 40px;
          height: 40px;
          border: 3px solid rgba(255, 255, 255, 0.1);
          border-top-color: var(--foreground);
          border-radius: 50%;
          animation: spin 1s linear infinite;
        }

        .status-text strong {
          display: block;
          font-size: 1.125rem;
          margin-bottom: 0.5rem;
          color: var(--foreground);
        }

        .status-text p {
          margin: 0;
          font-size: 0.875rem;
          color: var(--muted-foreground);
        }

        /* Premium Loading State */
        .loading-state-premium {
          padding: 3rem 2rem;
          border-radius: var(--radius);
          display: flex;
          flex-direction: column;
          align-items: center;
          gap: 2rem;
          text-align: center;
          background: rgba(0, 0, 0, 0.4);
          border: 1px solid rgba(255, 255, 255, 0.1);
          box-shadow: 0 20px 50px rgba(0, 0, 0, 0.5);
        }

        .loading-content {
          display: flex;
          flex-direction: column;
          align-items: center;
          gap: 1.5rem;
          position: relative;
          z-index: 10;
        }

        .animation-container {
          position: relative;
          width: 100px;
          height: 100px;
          display: flex;
          align-items: center;
          justify-content: center;
        }

        .sparkle-orbit {
          position: relative;
          animation: orbit 4s linear infinite;
        }

        .premium-sparkle-main {
          color: #ffffff;
          filter: drop-shadow(0 0 10px rgba(255, 255, 255, 0.8));
        }

        .scan-line {
          position: absolute;
          top: 0;
          left: 0;
          width: 100%;
          height: 2px;
          background: linear-gradient(90deg, transparent, #ffffff, transparent);
          box-shadow: 0 0 15px #ffffff;
          animation: scan 2s ease-in-out infinite;
          opacity: 0.5;
        }

        .status-text-premium h4 {
          font-size: 1.25rem;
          font-weight: 700;
          color: #ffffff;
          margin-bottom: 0.5rem;
          letter-spacing: 0.05em;
          text-transform: uppercase;
        }

        .status-text-premium p {
          font-size: 0.9rem;
          color: rgba(255, 255, 255, 0.6);
          margin-bottom: 1.5rem;
        }

        .progress-bar-container {
          width: 200px;
          height: 4px;
          background: rgba(255, 255, 255, 0.05);
          border-radius: 2px;
          overflow: hidden;
          margin: 0 auto;
        }

        .progress-bar-fill {
          width: 40%;
          height: 100%;
          background: linear-gradient(90deg, #333, #fff, #333);
          background-size: 200% 100%;
          border-radius: 2px;
        }

        @keyframes orbit {
          from { transform: rotate(0deg) translateY(5px) rotate(0deg); }
          to { transform: rotate(360deg) translateY(5px) rotate(-360deg); }
        }

        @keyframes scan {
          0%, 100% { transform: translateY(0); }
          50% { transform: translateY(100px); }
        }

        @keyframes shimmer {
          0% { background-position: -200% 0; }
          100% { background-position: 200% 0; }
        }

        .form-actions {
          display: flex;
          justify-content: flex-end;
          margin-top: 1rem;
        }

        :global(.submit-btn) {
          width: 100%;
        }

        /* Success State */
        .success-wrapper {
          position: relative;
          width: 100%;
          display: flex;
          justify-content: center;
        }

        .success-container {
          padding: 3rem;
          border-radius: var(--radius);
          text-align: center;
          display: flex;
          flex-direction: column;
          align-items: center;
          gap: 2rem;
          position: relative;
          overflow: hidden;
          width: 100%;
          max-width: 900px;
        }

        .success-header {
          display: flex;
          flex-direction: column;
          align-items: center;
          gap: 1rem;
        }

        .check-icon {
          width: 64px;
          height: 64px;
          background: #ffffff;
          color: #000000;
          border-radius: 12px;
          display: flex;
          align-items: center;
          justify-content: center;
          box-shadow: 0 0 20px rgba(255, 255, 255, 0.1);
        }

        .success-header h3 {
          margin: 0;
          font-size: 2rem;
          font-weight: 700;
          color: #ffffff;
        }

        .result-preview-grid {
          width: 100%;
          display: grid;
          gap: 1.5rem;
          margin: 1rem 0;
        }

        .result-preview-grid.single {
          grid-template-columns: 1fr;
          max-width: 600px;
        }

        .result-preview-grid.multi {
          grid-template-columns: repeat(2, 1fr);
        }

        @media (max-width: 600px) {
          .result-preview-grid.multi {
            grid-template-columns: 1fr;
          }
        }

        .result-item {
          position: relative;
          border-radius: var(--radius);
          overflow: hidden;
          transition: transform 0.3s ease;
        }

        .result-item:hover {
          transform: translateY(-4px);
        }

        .generated-image {
          width: 100%;
          height: auto;
          display: block;
          aspect-ratio: 16/9;
          object-fit: cover;
        }

        .result-actions-overlay {
          position: absolute;
          bottom: 0;
          left: 0;
          right: 0;
          padding: 1rem;
          background: linear-gradient(to top, rgba(0,0,0,0.8), transparent);
          display: flex;
          justify-content: center;
          gap: 0.5rem;
          opacity: 0;
          transition: opacity 0.2s ease;
        }

        .result-item:hover .result-actions-overlay {
          opacity: 1;
        }

        :global(.action-btn) {
          padding: 0.4rem 0.8rem !important;
          font-size: 0.75rem !important;
        }

        .success-actions {
          display: flex;
          gap: 1rem;
          margin-top: 1rem;
        }

        @keyframes spin {
          to { transform: rotate(360deg); }
        }

        @keyframes fade-in {
          from { opacity: 0; transform: translateY(20px); }
          to { opacity: 1; transform: translateY(0); }
        }

        @keyframes slide-down {
          from { opacity: 0; transform: translateY(-10px); }
          to { opacity: 1; transform: translateY(0); }
        }

        @keyframes scale-up {
          from { opacity: 0; transform: scale(0.95); }
          to { opacity: 1; transform: scale(1); }
        }

        @keyframes spin {
          to { transform: rotate(360deg); }
        }

        @keyframes fade-in {
          from { opacity: 0; transform: translateY(20px); }
          to { opacity: 1; transform: translateY(0); }
        }

        @keyframes slide-down {
          from { opacity: 0; transform: translateY(-10px); }
          to { opacity: 1; transform: translateY(0); }
        }

        @keyframes scale-up {
          from { opacity: 0; transform: scale(0.95); }
          to { opacity: 1; transform: scale(1); }
        }

        .fallback-warning-banner {
          border: 1px solid #eab308;
          background-color: rgba(234, 179, 8, 0.1);
          padding: 1rem;
          border-radius: 8px;
          margin-bottom: 1.5rem;
          display: flex;
          align-items: flex-start;
          gap: 1rem;
          text-align: left;
        }

        .warning-icon {
          color: #eab308;
          margin-top: 0.1rem;
        }

        .warning-title {
          color: #eab308;
          display: block;
          margin-bottom: 0.2rem;
          font-size: 15px;
        }

        .warning-message {
          margin: 0;
          color: rgba(255,255,255,0.8);
          font-size: 13px;
          line-height: 1.4;
        }
      `}</style>
    </div>
  );
}
